### ISSUE TITLE
For View() longer than Terminal height

### ISSUE THREAD

**Issue by Obsidian6s** [charmbracelet/bubbletea#19]
For the [basic tutorial](https://github.com/charmbracelet/bubbletea/tree/master/tutorials/basics), if the number of the `choices` is more than the height of the terminal, only the last lines can be viewed.

So is there any solutions to handle cases like this?

![image](https://user-images.githubusercontent.com/72505240/97113682-f74ac280-1726-11eb-851b-bef27ba7e102.png)

**Comment by meowgorithm** [comment]
There certainly is. You can put anything you'd like to scroll in a [Viewport](https://pkg.go.dev/github.com/charmbracelet/bubbles@v0.7.1/viewport), which is part of [Bubbles](https://github.com/charmbracelet/bubbles), the Bubble Tea standard component library.

If you want to navigate on an item-by-item basis (rather than treat the viewport like a pager) you'd need to define your own `Update` function to navigate; see [`LineUp`](https://pkg.go.dev/github.com/charmbracelet/bubbles@v0.7.1/viewport#Model.LineUp) and `LineDown`.

There's a [viewport example](https://github.com/charmbracelet/bubbletea/blob/master/examples/pager/main.go), though mind you it's in the context of a pager.

**Comment by meowgorithm** [comment]
@Obsidian6s just a small note that @KimMachineGun implemented exactly the UI you were asking about in [Modu](https://github.com/KimMachineGun/modu). The source code is straightforward and well-written.

![](https://github.com/KimMachineGun/modu/raw/master/preview.gif)
