### ISSUE TITLE
Why does bubbletea use strings/printf rather than a TUI library?

### ISSUE THREAD

**Issue by skuzzymiglet** [charmbracelet/bubbletea#21]
I'd like to ask why you decided to go with that architecture. tcell is much more cross-platform and performant than printf.

In a tcell-like environment `View() string` could become `View([][]Cell)`, which could reduce memory allocation. `Cell` would be a struct containing https://godoc.org/github.com/gdamore/tcell#CellBuffer.SetContent parameters

**Comment by meowgorithm** [comment]
Hi! We went with `View() string` because it's flexible, easy to understand, and usually fast enough for user interfaces.

One of the main things we wanted to do with Bubble Tea is allow other string-based rendering tools (like [Glamour](https://github.com/charmbracelet/glamour)) to operate with Bubble Tea very easily. Both of those libraries have very complex ANSI-based styling baked in that would be difficult to translate to a cell-based renderer.

We did find that scrolling on very large views with complex ANSI became an issue on slower terminals, so we added an optional [scroll-based rendering API](https://pkg.go.dev/github.com/charmbracelet/bubbletea#ScrollDown) that operates on a very low level, and works alongside the main renderer. The [`Viewport`](https://github.com/charmbracelet/bubbles#viewport) component takes advantage of this.

In terms of cross-platform compatibility, we thankfully haven't seen any issues so far with Linux, macOS and BSD.

Anyway, all this said, you're completely right about efficiency, and tcell does indeed do a great job there. We're exploring offering an alternative renderer (or renderers) with higher performance and more flexible layout capabilities.
