### ISSUE TITLE
Question about Design of `Cmd` in `Update(Msg) (Model, Cmd)`

### ISSUE THREAD

**Issue by HapYura** [charmbracelet/bubbletea#23]
In the original Elm Architecture, `Update()` just sends updated model to `View()`. Just like the figure below:

![drawing](https://user-images.githubusercontent.com/70552582/97541758-a675eb00-1a00-11eb-97a9-90c4af0069b1.png)

Whereas in Bubble Tea, `Update()` returns an newly updated model and also a command to execute asynchronously, which returns another message and henceforth invokes `Update()` again.

So can you please explain why Bubble Tea should be designed so, and what's the impact if the `Update()` is just `Update(Msg) Model` without `Cmd` in return (command would be executed in `Update()` directly sync-or-asynchronously then)?

**Comment by meowgorithm** [comment]
Hi! So the model you're describing above is Elm's [`Browser.sandbox`](https://package.elm-lang.org/packages/elm/browser/latest/Browser#sandbox), which doesn't include side effects:

```elm
update : msg -> model -> model
```

Since sandbox applications don't return commands, so they can't perform IO and interact with the outside world.

In Elm's [Browser.element](https://package.elm-lang.org/packages/elm/browser/latest/Browser#element), [Browser.document](https://package.elm-lang.org/packages/elm/browser/latest/Browser#document), and [Browser.application](https://package.elm-lang.org/packages/elm/browser/latest/Browser#application), however, the signature is more or less the same as we have in Bubble Tea:

```elm
update : msg -> model -> (model, Cmd msg)
```

In both Elm and Bubble Tea, commands runs asynchronously so that the model can be rendered immediately after an update, and so that long-running commands, such as a network call or timer, don't lock up the application while they're running.

I hope that answers your question. Let me know if you'd like more clarification.

**Comment by meowgorithm** [comment]
The other thing is that we have to return commands in `Update` so that the Bubble Tea runtime can receive the messages they return and pass those messages to the subsequent `Update`.

Anyway, happy to answer any other questions.
