### ISSUE TITLE
improve code coverage

### ISSUE THREAD

**Issue by phanirithvij** [charmbracelet/bubbletea#252]
The code coverage is [28.46% on coveralls](https://coveralls.io/github/charmbracelet/bubbletea).
Can tests be added and this be improved if possible?

I don't claim to know how bubbletea works internally and I think terminal based applications are hard to test, but if it is possible please add more thorough tests.

**Comment by bashbunni** [comment]
This is a wip :)

**Comment by LukaJaj** [comment]
Hey @bashbunni I would love to work on that. I just wrote my first test. You can review it here : https://github.com/charmbracelet/bubbletea/pull/356

**Comment by muesli** [comment]
Absolutely agreed, better test coverage is desired, and it's an on-going effort: we've recently managed to increase coverage to >55%. As such I'm going to close this issue, not because we're done with that effort, but because it doesn't address a specific improvement and thus isn't all too actionable.
