### ISSUE TITLE
Support for modals, overlapping windows

### ISSUE THREAD

**Issue by rambhosale** [charmbracelet/bubbletea#642]
I was looking for a way to add a small modal window to show a confirmation window in bubbletea app, I looked for something similar but couldn't find any exact feature like it, the best bubbletea compatible option I found is https://github.com/erikgeiser/promptkit#confirmation-prompt
It is somewhat similar but doesn't achieve the same feature that I need, if there is an existing option please let me know.

for reference, I am listing some similar options
from `github.com/jesseduffield/gocui`
![alt text](https://cloud.githubusercontent.com/assets/1223476/5992750/720b84f0-aa36-11e4-88ec-296fa3247b52.png "Title")

from `https://github.com/rivo/tview`
![alt text](https://github.com/rivo/tview/raw/master/demos/modal/screenshot.png "Title")

**Comment by meowgorithm** [comment]
Hi! Compositing is still a work in progress, however for now there's a PR in Lip Gloss that may get you most of the way there: https://github.com/charmbracelet/lipgloss/pull/102. See also [this note](https://github.com/charmbracelet/lipgloss/pull/102#issuecomment-1369844519) on how we recommend implementing it on your end.

Otherwise, please follow https://github.com/charmbracelet/bubbletea/issues/79 for updates.

(Duplicate of https://github.com/charmbracelet/bubbletea/issues/79)

**Comment by MoAlshatti** [comment]
Hi, any update on this?

**Comment by meowgorithm** [comment]
Hi! This is now available in [Lip Gloss v2 Beta](https://github.com/charmbracelet/lipgloss/releases/tag/v2.0.0-beta.2) and can be used to draw modals in Bubble Tea. We’ve been using it in production for quite some time.
