### ISSUE TITLE
Switching between list model and viewport model

### ISSUE THREAD

**Issue by nmin11** [charmbracelet/bubbletea#833]
**Describe the bug**
I want to implement a UI that switches between list and pager, like glow.
So I'm trying to do spikes using list and viewport models, but I've got some troubles with list view.

1. Title and filtering panel are not displayed.
2. In last page, non-existing items are printed. (items that were on the previous page fill in the empty spaces.)

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: macOS
 - Shell: zsh
 - Terminal Emulator: iterm2
 - Terminal Multiplexer: N/A

**To Reproduce**
Checkout my repo and run `go run .`

**Source Code**
https://github.com/nmin11/bubbletea-practice/blob/main/main.go

**Expected behavior**
Title should be present.
![스크린샷 2023-10-09 오후 2 36 33](https://github.com/charmbracelet/bubbletea/assets/75058239/77ef5198-71bf-4b25-aef0-f60dc7e79d26)

Non-existing item should not be printed.
![스크린샷 2023-10-09 오후 2 37 19](https://github.com/charmbracelet/bubbletea/assets/75058239/837212e9-e5c9-4997-8bce-e0322de05758)

**Screenshots**
In my case,
Title part is missing.
![스크린샷 2023-10-09 오후 2 36 10](https://github.com/charmbracelet/bubbletea/assets/75058239/417c7bab-e49b-4143-9b67-25543bef4aec)

Last page print strange items
![스크린샷 2023-10-09 오후 2 36 55](https://github.com/charmbracelet/bubbletea/assets/75058239/d3278ba2-2b8f-42c2-9360-42894b8651d6)

**Additional context**
In fact, I want to solve one question.
If I want to create a TUI like glow, do I have to generate my own list model like glow?

**Comment by A-Daneel** [comment]
not exactly sure if I completely understand your questions.

As for the title and search not showing, unless I'm mistaken it's due to your list taking up all available space [see these lines in your repo](https://github.com/nmin11/bubbletea-practice/blob/c06e1c1b1b7f32b6ec6646dc258a04a7fa6b82ff/main.go#L40C3-L40C3).

The second issue I was unable to reproduce, it could also have been a side effect from the fact that the list was taking up more space then there was (not completely sure how the rendering works).

**Comment by nmin11** [comment]
OMG you were right.
After modifying the Height value of the size, I can see title and search.
And last page also printed normally.
thank so much, I should be carefully handle that size value.
