### ISSUE TITLE
Create overlap views

### ISSUE THREAD

**Issue by gczgcz2015** [charmbracelet/bubbletea#859]
how can i create overlap views like lazygit
![image](https://github.com/charmbracelet/bubbletea/assets/15188637/df623ce9-fa94-4a04-baee-fae9a7a57477)

**Comment by wolfmagnate** [comment]
@gczgcz2015 
You probably need to use lipgloss rather than bubble tea to create this view. bubble tea simply draws the `View`'s return values to the screen, and is not responsible for how they are styled. 
If lipgloss does not have enough functionality to do what you want, you should create an issue in lipgloss.

**Comment by gczgcz2015** [comment]
> @gczgcz2015 You probably need to use lipgloss rather than bubble tea to create this view. bubble tea simply draws the `View`'s return values to the screen, and is not responsible for how they are styled. If lipgloss does not have enough functionality to do what you want, you should create an issue in lipgloss.

thank you very much
