### ISSUE TITLE
Kitty Keyboard Protocol

### ISSUE THREAD

**Issue by Broderick-Westrope** [charmbracelet/bubbletea#869]
**Is your feature request related to a problem? Please describe.**
It would be nice to see a solution to detecting key release events. Currently, for any action that requires this functionality in my Bubbletea apps I have replaced it with pressing the key to toggle which is less than ideal.

**Describe the solution you'd like**
The ideal solution would be to have an `actionType` (or similar) field that determines what happened (press, release, etc). Unfortunately, this would likely break a lot of existing code, so another solution would be to add release versions of all the basic keys.

**Describe alternatives you've considered**
I've considered cloning the Bubbletea package for projects that require it, and adding the functionality using solutions such as [gohook](https://github.com/robotn/gohook). I am unsure of other potential solutions.

**Additional context**
If anyone has other ideas of how this could be achieved, either on my own or how I could implement this better into the Bubbletea package, please let me know!

**Comment by meowgorithm** [comment]
Hi! So if you're targeting all terminals you simply cannot detect release events (terminal input handing is rather archaic).

We can, however, offer support release events, when available, with the [Kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#fixterms-bugs). Keep in mind, however, that there are only a few terminals that support the protocol at the moment.

## Maintainer's notes:

fixterms/`CSI u` (https://github.com/charmbracelet/bubbletea/issues/293), also proposed, does not support key release events. The Kitty keyboard is mostly backwards compatible with this protocol, but not entirely.

A large, high fidelity range of input options, including key release, are available in Windows as evidenced in https://github.com/charmbracelet/bubbletea/pull/140. We didn't merge that because of the large amount of Windows-only code and the maintenance burden that would come with it.

**Comment by meowgorithm** [comment]
Just a note that this is currently in development on the [`term-input`](https://github.com/charmbracelet/bubbletea/tree/term-input) branch.

**Comment by Broderick-Westrope** [comment]
Hey @meowgorithm, wondering if there is any update on this? I notice that the branch went untouched very quickly (March 1st). Has the work moved elsewhere or is there a plan for future implementation of the Kitty keyboard protocol? Thanks

**Comment by ajayd-san** [comment]
Same, I'm also waiting for this to be implemented. I'd like to take the issue up if no one is working on it

**Comment by meowgorithm** [comment]
Hi all! This is indeed in active development; we’ve moved the feature around a few branches. We were planning on including it as part of a larger update but we may break it out to get it implemented sooner. We’ll keep this issue updated with progress.
